---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-verify
spec:
  params:
    - name: directory-name
      description: directory containing source code
  steps:
    - name: task-verify
      image: shri4u/pytest
      workingDir: "/artifacts"
      env:
        - name: REPOSITORY_DIRECTORY
          value: $(params.directory-name)

      command: ["/bin/bash", "-c"]
      args:
          - |
          set -e pipefail
          pip install in-toto
          cd in-toto/flat-directory
          in-toto-verify --verbose --layout root.layout --layout-key alice.pub

  workspaces:
    - name: artifacts
      mountPath: /artifacts
