---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-python-repo
spec:
  params:
    - name: directory-name
      description: directory containing source code
  steps:
    - name: clone-python-repo
      image: shri4u/pytest
      workingDir: "/artifacts"
      env:
        - name: REPOSITORY_DIRECTORY
          value: $(params.directory-name)

      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e pipefail
          git clone https://AUTH-TOKEN@github.com/pluralsight/intro-to-pytest.git

  workspaces:
    - name: artifacts
      mountPath: /artifacts
