---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-pytest
spec:
  params:
    - name: directory-name
      description: directory containing source code
  steps:
    - name: pytest
      image: shri4u/pytest
      workingDir: "/artifacts"
      env:
        - name: REPOSITORY_DIRECTORY
          value: $(params.directory-name)

      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e pipefail

          pytest $(REPOSITORY_DIRECTORY)/

  workspaces:
    - name: artifacts
      mountPath: /artifacts
