---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: in-toto-create_layout
spec:
  params:
    - name: directory-name
      description: directory containing source code
  steps:
    - name: create_int_toto_layout
      image: shri4u/pytest
      workingDir: "/artifacts"
      env:
        - name: REPOSITORY_DIRECTORY
          value: $(params.directory-name)

      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e pipefail
          pip install in-toto
          
  workspaces:
    - name: artifacts
      mountPath: /artifacts
