apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-demo
spec:
  tasks:
    - name: junit-testing
      taskRef: 
        name: echo-hello-world
    - name: vulnerability-check 
      taskRef:
        name: echo-hello-world
    - name: connectivity-check
      taskRef:
        name: echo-hello-world
    - name: int-toto-check
      taskRef:
        name: echo-hello-world
    
