---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-pytest-original
spec:
  params:
    - name: directory-name
      description: directory containing source code
  steps:
    - name: pytest
      image: shri4u/pytest
      workingDir: "/artifacts"
      env:
        - name: REPOSITORY_DIRECTORY
          value: $(params.directory-name)

      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e pipefail
          echo "demo 4"
          pytest intro-to-pytest/tests/00_empty_test.py


  workspaces:
    - name: artifacts
      mountPath: /artifacts
